name: Deploy .NET Framework App to Azure App Service

on:
  push:
    branches:
      - main  # Trigger on push to the main branch.

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up MSBuild environment
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    # Step 3: Install NuGet
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    # Step 4: Restore NuGet packages
    - name: Restore NuGet Packages
      run: nuget restore TestAppService.sln

    # Step 5: Build and publish the application
    - name: Build and Publish
      run: |
        msbuild TestAppService.csproj /p:Configuration=Release /p:DeployOnBuild=true /p:WebPublishMethod=FileSystem /p:publishUrl="${{ github.workspace }}/publish"

    # Step 6: Zip the published files
    - name: Archive Published Files
      run: |
        powershell Compress-Archive -Path "${{ github.workspace }}/publish/*" -DestinationPath "${{ github.workspace }}/app.zip"

    # Step 7: Deploy to Azure App Service
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'test-net'  # Replace with your App Service name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: "${{ github.workspace }}/app.zip"
