name: Deploy .NET Framework App to Azure App Service

on:
  push:
    branches:
      - main  # Trigger on push to the main branch.

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up MSBuild environment
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    # Step 3: Install NuGet
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    # Step 4: Restore NuGet packages
    - name: Restore NuGet Packages
      run: nuget restore TestAppService.sln

    # Step 5: Build and publish the application
    - name: Build and Publish
      shell: cmd
      run: |
        msbuild TestAppService\TestAppService.csproj ^
          /p:Configuration=Release ^
          /p:OutDir="${{ github.workspace }}\publish" ^
          /p:DeployOnBuild=true

    # Step 6: Debug Build Output
    - name: Debug Build Output
      run: dir "${{ github.workspace }}\publish" /s

    # Step 7: Zip the Published Files
    - name: Archive Published Files
      if: success() && steps.debug.outputs.exists == 'true'
      run: |
        powershell Compress-Archive -Path "${{ github.workspace }}\publish\*" -DestinationPath "${{ github.workspace }}\app.zip"

    # Step 8: Deploy to Azure App Service
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'test-net'  # Replace with your App Service name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: "${{ github.workspace }}/app.zip"
