name: Deploy .NET Framework App to Azure App Service

on:
  push:
    branches:
      - main  # Trigger on push to the main branch.
env:
  AZURE_WEBAPP_NAME: test-net
  AZURE_WEBAPP_PACKAGE_PATH: 'D:\a\net.4.8.1-azure-test\net.4.8.1-azure-test\bin\'
jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up MSBuild environment
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    # Step 3: Install NuGet
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    # Step 4: Restore NuGet packages
    - name: Restore NuGet Packages
      run: nuget restore TestAppService.sln

    # Step 5: Build and publish the application
    - name: Build
      run: |
        msbuild TestAppService.sln /t:Build /p:Configuration=Release /p:Platform="Any CPU" /verbosity:minimal

    # Step 7: Published Files
    - name: Published Files
      run: |
        msbuild TestAppService.sln /t:Publish /p:Configuration=Release /p:Platform="Any CPU" /p:PublishDir="./artifacts"

    # Step 8: Deploy to Azure App Service
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{env.AZURE_WEBAPP_NAME}}  # Replace with your App Service name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: artifacts/
        #package: "${{ github.workspace }}/app.zip"
